# Generated by Django 2.1.4 on 2020-01-11 17:14

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('attribute_id', models.ForeignKey(on_delete=None, to='product.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('category_id', models.ForeignKey(on_delete=None, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSKUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_uuid', models.CharField(default=product.models.f, max_length=20, unique=True)),
                ('product_id', models.ForeignKey(on_delete=None, related_name='product_skus', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SKUValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=None, to='product.Product')),
                ('sku_id', models.ForeignKey(on_delete=None, related_name='sku_values', to='product.ProductSKUs')),
                ('value_id', models.ForeignKey(on_delete=None, to='product.AttributeValues')),
            ],
        ),
    ]
