# Generated by Django 4.2 on 2023-04-12 16:06

import django.db.models.deletion
from django.db import migrations, models

import product.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Color', 'Size' etc.",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Kg', 'Litre' etc. It can be left blank.",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttributeValues",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="e.g. 'Red', 'Green', 'Small', 1, 5 etc.",
                        max_length=200,
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="product.attribute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Fruits', 'Clothes' etc.",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="'Apple', 'Banana', 'T-Shirt' etc.",
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Better to upload small size images",
                        null=True,
                        upload_to="products",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="product.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSKUs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        default=product.models.unique_id,
                        editable=False,
                        help_text="Auto generated unique code",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="product_skus",
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SKUValues",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="product.attributevalues",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="product.product",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sku_values",
                        to="product.productskus",
                    ),
                ),
            ],
        ),
    ]
