# Generated by Django 2.0.2 on 2018-07-14 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180204_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
