# Generated by Django 4.2 on 2023-04-12 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Purchased at"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Sold at"
                    ),
                ),
                ("discount", models.FloatField(default=0.0)),
            ],
            options={
                "permissions": (("read_item", "Can read item"),),
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Green Grocer', 'ABC Store' etc.",
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="e.g. 'Kathmandu, Nepal' etc.", max_length=250
                    ),
                ),
                ("phone", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SaleProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                (
                    "sale_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transaction.sale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("sold_quantity", models.IntegerField(default=0)),
                ("purchase_price_per_unit", models.FloatField()),
                ("sale_price_per_unit", models.FloatField()),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="transaction.purchase",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="purchase",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="transaction.supplier"
            ),
        ),
    ]
