# Generated by Django 3.2.5 on 2021-07-20 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Purchased at')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sold at')),
                ('discount', models.FloatField(default=0.0)),
            ],
            options={
                'permissions': (('read_item', 'Can read item'),),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_uuid', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('sale_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.sale')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_uuid', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('sold_quantity', models.IntegerField(default=0)),
                ('purchase_price_per_unit', models.FloatField()),
                ('sale_price_per_unit', models.FloatField()),
                ('purchase_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.supplier'),
        ),
    ]
