# Generated by Django 2.2.9 on 2020-01-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='purchase_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.Purchase'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sale_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.Sale'),
        ),
    ]
